apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  # Настройка для DockerHub или локального репо
  registries.conf: |
    registries:
    - name: DockerHub
      api_url: https://index.docker.io
      prefix: index.docker.io
      credentials: pullsecret:argocd/dockerhub-creds