apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: f9

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
- name: base-app-config
  literals:
    - ASPNETCORE_ENVIRONMENT=Development
    - AzureAppConfigurationHostUrl=https://fora-dev-app-conf.azconfig.io
    - AZURE_CLIENT_ID=951920b5-511a-4ff9-a4e2-3966a2f34b71