apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service

resources:
  - ../../../base/node-red
  
commonAnnotations:
  # Використовуємо офіційний шлях nodered/node-red
  argocd-image-updater.argoproj.io/image-list: "nodered=docker.io/nodered/node-red"
  argocd-image-updater.argoproj.io/nodered.update-strategy: semver
  argocd-image-updater.argoproj.io/write-back-method: argocd

images:
  - name: docker.io/nodered/node-red
    newName: docker.io/nodered/node-red
    newTag: 4.0.0 # Поточна стабільна версія (або вкажіть потрібну)